### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by heuwerk** [nuspell/nuspell#124]
The issues can be of three types (delete two rows and leave only one):

- Others, questions

# Other issues

Dear developers,
I have a question about the licensing of the project.

I am a User of GrapheneOS and they tried to replace the AOSP Keyboard with [Floris Board](https://github.com/florisboard/florisboard)
Unfortunately, the developers of GrapheneOS cannot or do not want to include code under the (L)GPLv3 in their operating system (see this [Issue](https://github.com/GrapheneOS/os-issue-tracker/issues/579#issuecomment-1119288286)). 

Therefore my question, if it would be possible to dual license this software under a permissive Open Source License, like the Apache License.

I am not a lawyer or legal expert in any way, but would wish that a solution could be found for this problem.

**Comment by dimztimz** [comment]
Sorry this is impossuble. The problem is on their side.

**Comment by thestinger** [comment]
We choose not to use licenses restricting how the code can be used, which despite the LGPLv3 and GPLv3 doing that is stated as something that makes software non-free by the FSF. LGPLv3 and GPLv3 are even compatible with LGPLv2 and GPLv2 projects which chose not to trust the FSF to arbitrarily change the licenses going forward.

It's not a problem on our side. It's a decision we made because we don't define software freedom the way you do and we want GrapheneOS to be usable for any purpose including a vendor using our work to make a locked down device / appliance.

We plan on addressing the issue in FlorisBoard.

**Comment by thestinger** [comment]
And to be clear we have no plans to ever make those kinds of locked down devices ourselves but providing the freedom for others to use our code that way is important to us both out of principle and because we really need collaboration with smartphone OEMs and that is what they want. If we don't meet the expectations they have for licensing we would largely rule out those partnerships the way we want them to happen. They shouldn't have to remove bits and pieces of GrapheneOS to go back to having GPLv2-only (with classpath exception for the Java standard libraries, etc. similar to how the kernel API works for userspace) and permissive licensing for everything else.
