### ISSUE TITLE
Does Nuspell support infixes?

### ISSUE THREAD

**Issue by mhmd-azeez** [nuspell/nuspell#26]
# Other issues

I am trying to make a spell checker for Kurdish. The problem is, Kurdish relies a lot on infixes (mostly because of clitic pronouns). I'd appreciate it if your provide any guidance on what's the best approach for a language like that.

## If Nuspell supports Infixes

That's great news, It'd rather create a Nuspell dictionary than a custom library on my own.

## If Nuspell doesn't support Infixes and there aren't any reasonable ways to workaround that limitation

I have noticed that Hunspell uses very little memory and is quite fast. So if I want to create a custom library for Kurdish, I want to know which algorithms Hunspell uses.

Here is a general idea of what I am trying to accomplish:

Consider this word: Bexshin (Forgiving), It can come in these forms:

 - Bi**m**bexsh**e** => [You] Forgive me
 - Bi**t**bexsh**m** => [I] Forgive you
 - Bi**yan**bexsh**e** => [You] Forgive them
 - And many more!

Instead of a list of words, we can have a list of patterns like so: `Bi{pronoun}bexsh{pronoun}`

More Examples:

Eat (`Dexo{pronoun}`)
- **I** eat => Dexo**m**
- **We** eat => Dexo**yn**
- **They** eat => Dexo**n**

Can be represented as: 

Work (`Kar{pronoun}dekrid`)
- **I** worked => Kar**m**dekird
- **He** Worked => Kar**î**dekird
- **They** worked => Kar**yan**dekird

So I need an algorithm to very quickly tell me what are the closest matching patterns, and then I can expand only those patterns and based on the Levenshtein distance to the input word give back a list of suggestions.

I know that I can read the source code, and I will. But it'd make my job much easier if you gave me a few leads on which algorithms can be useful based on your experience.

**Comment by baarsrj** [comment]
You might have a look at the documents for Hunspell. NUspell is promised to be compatible, so most what is there in the documentation for parameters should still be valid.
Chaining word building blocks is not that difficult; The flexing for eat par example is simply done by affixes. Coordinating an infix with an affix as in Biyanbexshe might be difficult, but as far as I know it can be done.
It could be usefull hoewever, to have all very common words in a plain list, using only affixes and prefixes, since suggestions generated are best then.
Though I don't know any word of Kurdish, I might be able to help a bit. Might be best to start with a word frequency list and a defined allowed character set.

**Comment by encrypt0r** [comment]
@baarsrj Thank you for your reply. Fortunately, I already have a [wordlist with frequencies](https://github.com/DevelopersTree/KurdishResources/blob/master/Corpus/All%20Words-Normalized.xlsx) (Although the words are in the Arabic alphabet, not Latin. But I can convert them for you if you are interested).

I have tried a few times but to me, it seems that for words like `Biyanbexshe`, we need specific affix rules for each word (or maybe group of words that start with the same prefixes). And the problem is, every transitive verb in Kurdish can have two clitic pronouns in it. So I am concerned about the affix file size and performance.

**Comment by encrypt0r** [comment]
P.S [here is a thread](https://sourceforge.net/p/hunspell/mailman/message/30034935/) from the Hunspell mail list about creating a Kurdish dictionary for Hunspell.

**Comment by baarsrj** [comment]
I do not understand you worries. Contact me at info at taaltik.nl

Verzonden van mijn mobiele telefoon.
