### ISSUE TITLE
Python check

### ISSUE THREAD

**Issue by MayuraVerma** [nuspell/nuspell#40]
# Other issues

Is it possible to use nuspell with python?

I wanted to use hunspell with python. I got stuck with installation https://github.com/blatinier/pyhunspell/issues/67

**Comment by PanderMusubi** [comment]
Not yet. Language bindings are not planned for version 3, probably for version 4. If you want to make them yourself, please align the choice of framework or generator used with us before starting on it.

**Comment by MayuraVerma** [comment]
Thank you.
But is the timeline for version 3 and 4?
I hope, it is few months.

**Comment by PanderMusubi** [comment]
Version 3 hopefully before FOSDEM, but no promises

**Comment by dimztimz** [comment]
I'm leaving this only as a note, no promises. There are 3 tools that might help:

1. Boost Python
2. pybind11
3. SWIG.

Work for this should be done in a separate repository.

**Comment by PanderMusubi** [comment]
There were some people at Nuspell's info stand at FOSDEM that wanted to work on this, also for other languages. They would contact us via an issue here. Looking forward to those contributions.

What they also told me regarding language bindings in general is the following: 1. It is advisable to make a language binding when you have already experience with it, since it is a special skill. 2. Use the latest technology available, do not fork an old language binding from another project. 3. Know your way around locales and character encodings and provide tests for those.

**Comment by mbarkhau** [comment]
I think I could hack together a wrapper for the cli relatively quickly. Include the binary in a package and just interact with the subprocess via stdin/stdout. Is the api of the cli stable? 

Also, would be nice if binaries for various platforms were available, I'm not sure I want to try cross compilation.

**Comment by PanderMusubi** [comment]
The API regarding checking the spelling and getting suggestions is stable. Personal dictionaries is not yet fully implemented, so best is to not yet use that part. Both pynuspell and pyspelling are welcome to support Nuspell. We have binary library bulids for many platforms, see https://github.com/nuspell/nuspell/wiki/Nuspell-packaged-binaries Use the libraries directly, do not wrap the cli application as it also does not yet fully support personal dictionaries and at the moment is more prone to changes than the library API. We prefer proper language support rather than a quickly hacked together solution. Perhaps it is best to join forces to get one well-developed and well-maintined Python language binding to Nuspell.

**Comment by scherzocrk** [comment]
In case you are still interested, I've created Python bindings for nuspell over here https://github.com/scherzocrk/pynuspell

**Comment by dimztimz** [comment]
Closing this because there is other issue now #110.
